# Generated by Django 5.1.4 on 2025-03-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('edad', models.IntegerField(default=0)),
                ('escuela', models.IntegerField(default=0)),
                ('grado', models.IntegerField(default=0)),
                ('turno', models.CharField(default='', max_length=1)),
                ('dni', models.IntegerField(default=0)),
                ('grupo_familiar', models.CharField(default='', max_length=50)),
                ('tel_contacto', models.IntegerField(default=0)),
                ('nombre_tutor', models.CharField(default='', max_length=20)),
                ('dni_tutor', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('inasistencias', models.IntegerField(default=0)),
                ('profesionales', models.CharField(default='', max_length=1000)),
                ('observaciones', models.TextField(default='')),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(default='', max_length=30)),
                ('turno_profesor', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(default='', max_length=30)),
                ('numero', models.IntegerField(default=0)),
                ('direccion', models.CharField(default='', max_length=30)),
                ('tel_escuela', models.IntegerField(default=0)),
                ('mail_escuela', models.CharField(default='', max_length=30)),
                ('nombre_directivo', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
