# Generated by Django 5.1.4 on 2025-01-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(default='', max_length=30)),
                ('numero', models.IntegerField(default=0)),
                ('direccion', models.CharField(default='', max_length=30)),
                ('tel_escuela', models.IntegerField(default=0)),
                ('mail_escuela', models.CharField(default='', max_length=30)),
                ('nombre_directivo', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
