# Generated by Django 5.1.4 on 2025-01-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='asistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni_tutor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='escuela',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo_familiar',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='inasistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre_tutor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='observaciones',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='alumno',
            name='profesionales',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tel_contacto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='turno',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='alumno',
            name='turno_profesor',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], default='T', max_length=1),
        ),
    ]
