# Generated by Django 5.1.4 on 2025-02-25 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_alumno_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True),
        ),
    ]
