# Generated by Django 5.1.4 on 2025-03-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_alumno_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
