# Generated by Django 5.1.4 on 2025-02-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alumno_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
