# Generated by Django 5.1.4 on 2025-02-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_alumno_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(default='', max_length=30),
        ),
    ]
